/*Copyright (c) 2018-2019 cmt.mu All Rights Reserved.
 This software is the confidential and proprietary information of cmt.mu You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with cmt.mu*/
package com.mu.cmt.pfs.pfsdb.models.procedure;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/


import java.io.Serializable;
import java.util.List;
import java.util.Objects;

import com.wavemaker.runtime.data.annotations.ColumnAlias;

public class ProcRf2000pk0OclovgetAllLovResponsePoutAllLov implements Serializable {


    @ColumnAlias("ALLLOV")
    private String alllov;

    @ColumnAlias("LOVDES")
    private String lovdes;

    public String getAlllov() {
        return this.alllov;
    }

    public void setAlllov(String alllov) {
        this.alllov = alllov;
    }

    public String getLovdes() {
        return this.lovdes;
    }

    public void setLovdes(String lovdes) {
        this.lovdes = lovdes;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof ProcRf2000pk0OclovgetAllLovResponsePoutAllLov)) return false;
        final ProcRf2000pk0OclovgetAllLovResponsePoutAllLov procRf2000pk0oclovgetAllLovResponsePoutAllLov = (ProcRf2000pk0OclovgetAllLovResponsePoutAllLov) o;
        return Objects.equals(getAlllov(), procRf2000pk0oclovgetAllLovResponsePoutAllLov.getAlllov()) &&
                Objects.equals(getLovdes(), procRf2000pk0oclovgetAllLovResponsePoutAllLov.getLovdes());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getAlllov(),
                getLovdes());
    }
}