/*Copyright (c) 2018-2019 cmt.mu All Rights Reserved.
 This software is the confidential and proprietary information of cmt.mu You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with cmt.mu*/
package com.mu.cmt.pfs.pfsdb.models.procedure;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/


import java.io.Serializable;
import java.util.List;
import java.util.Objects;

import com.wavemaker.runtime.data.annotations.ColumnAlias;

public class ProcRf2000pk0OclovgetShpDestLovResponsePoutShpDestLov implements Serializable {


    @ColumnAlias("SHPDESTCOD")
    private String shpdestcod;

    public String getShpdestcod() {
        return this.shpdestcod;
    }

    public void setShpdestcod(String shpdestcod) {
        this.shpdestcod = shpdestcod;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof ProcRf2000pk0OclovgetShpDestLovResponsePoutShpDestLov)) return false;
        final ProcRf2000pk0OclovgetShpDestLovResponsePoutShpDestLov procRf2000pk0oclovgetShpDestLovResponsePoutShpDestLov = (ProcRf2000pk0OclovgetShpDestLovResponsePoutShpDestLov) o;
        return Objects.equals(getShpdestcod(), procRf2000pk0oclovgetShpDestLovResponsePoutShpDestLov.getShpdestcod());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getShpdestcod());
    }
}