/*Copyright (c) 2018-2019 cmt.mu All Rights Reserved.
 This software is the confidential and proprietary information of cmt.mu You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with cmt.mu*/
package com.mu.cmt.pfs.pfsdb.models.procedure;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/


import java.io.Serializable;
import java.util.List;
import java.util.Objects;

import com.wavemaker.runtime.data.annotations.ColumnAlias;

public class ProcRf2000pk0OclovgetCalcMethodLovResponsePoutCalcMethodLov implements Serializable {


    @ColumnAlias("CALCMETHOD")
    private String calcmethod;

    @ColumnAlias("QTYUOM")
    private String qtyuom;

    public String getCalcmethod() {
        return this.calcmethod;
    }

    public void setCalcmethod(String calcmethod) {
        this.calcmethod = calcmethod;
    }

    public String getQtyuom() {
        return this.qtyuom;
    }

    public void setQtyuom(String qtyuom) {
        this.qtyuom = qtyuom;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof ProcRf2000pk0OclovgetCalcMethodLovResponsePoutCalcMethodLov)) return false;
        final ProcRf2000pk0OclovgetCalcMethodLovResponsePoutCalcMethodLov procRf2000pk0oclovgetCalcMethodLovResponsePoutCalcMethodLov = (ProcRf2000pk0OclovgetCalcMethodLovResponsePoutCalcMethodLov) o;
        return Objects.equals(getCalcmethod(), procRf2000pk0oclovgetCalcMethodLovResponsePoutCalcMethodLov.getCalcmethod()) &&
                Objects.equals(getQtyuom(), procRf2000pk0oclovgetCalcMethodLovResponsePoutCalcMethodLov.getQtyuom());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getCalcmethod(),
                getQtyuom());
    }
}