/*Copyright (c) 2018-2019 cmt.mu All Rights Reserved.
 This software is the confidential and proprietary information of cmt.mu You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with cmt.mu*/
package com.mu.cmt.pfs.pfsdb.models.procedure;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/


import java.io.Serializable;
import java.util.List;
import java.util.Objects;

import com.wavemaker.runtime.data.annotations.ColumnAlias;

public class ProcRf2000pk0OclovgetAllShpDestLovResponsePoutAllShpDestLov implements Serializable {


    @ColumnAlias("ALLSHPDESTCOD")
    private String allshpdestcod;

    public String getAllshpdestcod() {
        return this.allshpdestcod;
    }

    public void setAllshpdestcod(String allshpdestcod) {
        this.allshpdestcod = allshpdestcod;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof ProcRf2000pk0OclovgetAllShpDestLovResponsePoutAllShpDestLov)) return false;
        final ProcRf2000pk0OclovgetAllShpDestLovResponsePoutAllShpDestLov procRf2000pk0oclovgetAllShpDestLovResponsePoutAllShpDestLov = (ProcRf2000pk0OclovgetAllShpDestLovResponsePoutAllShpDestLov) o;
        return Objects.equals(getAllshpdestcod(), procRf2000pk0oclovgetAllShpDestLovResponsePoutAllShpDestLov.getAllshpdestcod());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getAllshpdestcod());
    }
}