/*Copyright (c) 2018-2019 cmt.mu All Rights Reserved.
 This software is the confidential and proprietary information of cmt.mu You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with cmt.mu*/
package com.mu.cmt.pfs.pfsdb.models.procedure;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/


import java.io.Serializable;
import java.util.List;
import java.util.Objects;

import com.wavemaker.runtime.data.annotations.ColumnAlias;

public class ProcRf2000pk0OclovgetQtyUomLovResponsePoutQtyUomLov implements Serializable {


    @ColumnAlias("QTYUOM")
    private String qtyuom;

    @ColumnAlias("RANGEHIDE")
    private String rangehide;

    @ColumnAlias("PERCENTAGEHIDE")
    private String percentagehide;

    public String getQtyuom() {
        return this.qtyuom;
    }

    public void setQtyuom(String qtyuom) {
        this.qtyuom = qtyuom;
    }

    public String getRangehide() {
        return this.rangehide;
    }

    public void setRangehide(String rangehide) {
        this.rangehide = rangehide;
    }

    public String getPercentagehide() {
        return this.percentagehide;
    }

    public void setPercentagehide(String percentagehide) {
        this.percentagehide = percentagehide;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof ProcRf2000pk0OclovgetQtyUomLovResponsePoutQtyUomLov)) return false;
        final ProcRf2000pk0OclovgetQtyUomLovResponsePoutQtyUomLov procRf2000pk0oclovgetQtyUomLovResponsePoutQtyUomLov = (ProcRf2000pk0OclovgetQtyUomLovResponsePoutQtyUomLov) o;
        return Objects.equals(getQtyuom(), procRf2000pk0oclovgetQtyUomLovResponsePoutQtyUomLov.getQtyuom()) &&
                Objects.equals(getRangehide(), procRf2000pk0oclovgetQtyUomLovResponsePoutQtyUomLov.getRangehide()) &&
                Objects.equals(getPercentagehide(), procRf2000pk0oclovgetQtyUomLovResponsePoutQtyUomLov.getPercentagehide());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getQtyuom(),
                getRangehide(),
                getPercentagehide());
    }
}