/*Copyright (c) 2018-2019 cmt.mu All Rights Reserved.
 This software is the confidential and proprietary information of cmt.mu You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with cmt.mu*/
package com.mu.cmt.pfs.pfsdb.models.procedure;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/


import java.io.Serializable;
import java.util.List;
import java.util.Objects;

import com.wavemaker.runtime.data.annotations.ColumnAlias;

public class ProcRf2000pk0OrlovgetCligrpResponsePoutCligrpLov implements Serializable {


    @ColumnAlias("CLIGRP")
    private String cligrp;

    public String getCligrp() {
        return this.cligrp;
    }

    public void setCligrp(String cligrp) {
        this.cligrp = cligrp;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof ProcRf2000pk0OrlovgetCligrpResponsePoutCligrpLov)) return false;
        final ProcRf2000pk0OrlovgetCligrpResponsePoutCligrpLov procRf2000pk0orlovgetCligrpResponsePoutCligrpLov = (ProcRf2000pk0OrlovgetCligrpResponsePoutCligrpLov) o;
        return Objects.equals(getCligrp(), procRf2000pk0orlovgetCligrpResponsePoutCligrpLov.getCligrp());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getCligrp());
    }
}