/*Copyright (c) 2018-2019 cmt.mu All Rights Reserved.
 This software is the confidential and proprietary information of cmt.mu You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with cmt.mu*/
package com.mu.cmt.pfs.pfsdb.models.procedure;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/


import java.io.Serializable;
import java.util.List;
import java.util.Objects;

import com.wavemaker.runtime.data.annotations.ColumnAlias;

public class ProcOc1000pk0FreightgetAllLovResponse implements Serializable {


    @ColumnAlias("pOutAllLOV")
    private List<ProcOc1000pk0FreightgetAllLovResponsePoutAllLov> poutAllLov;

    public List<ProcOc1000pk0FreightgetAllLovResponsePoutAllLov> getPoutAllLov() {
        return this.poutAllLov;
    }

    public void setPoutAllLov(List<ProcOc1000pk0FreightgetAllLovResponsePoutAllLov> poutAllLov) {
        this.poutAllLov = poutAllLov;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof ProcOc1000pk0FreightgetAllLovResponse)) return false;
        final ProcOc1000pk0FreightgetAllLovResponse procOc1000pk0freightgetAllLovResponse = (ProcOc1000pk0FreightgetAllLovResponse) o;
        return Objects.equals(getPoutAllLov(), procOc1000pk0freightgetAllLovResponse.getPoutAllLov());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getPoutAllLov());
    }
}