/*Copyright (c) 2018-2019 cmt.mu All Rights Reserved.
 This software is the confidential and proprietary information of cmt.mu You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with cmt.mu*/
package com.mu.cmt.pfs.pfsdb.models.procedure;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/


import java.io.Serializable;
import java.util.List;
import java.util.Objects;

import com.wavemaker.runtime.data.annotations.ColumnAlias;

public class ProcOc1000pk0FreightgetFreightTermResponsePoutFreightTerm implements Serializable {


    @ColumnAlias("FREIGHT_TERM")
    private String freightTerm;

    @ColumnAlias("SHPITEMCAT")
    private String shpitemcat;

    @ColumnAlias("SHPITEMDES")
    private String shpitemdes;

    public String getFreightTerm() {
        return this.freightTerm;
    }

    public void setFreightTerm(String freightTerm) {
        this.freightTerm = freightTerm;
    }

    public String getShpitemcat() {
        return this.shpitemcat;
    }

    public void setShpitemcat(String shpitemcat) {
        this.shpitemcat = shpitemcat;
    }

    public String getShpitemdes() {
        return this.shpitemdes;
    }

    public void setShpitemdes(String shpitemdes) {
        this.shpitemdes = shpitemdes;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof ProcOc1000pk0FreightgetFreightTermResponsePoutFreightTerm)) return false;
        final ProcOc1000pk0FreightgetFreightTermResponsePoutFreightTerm procOc1000pk0freightgetFreightTermResponsePoutFreightTerm = (ProcOc1000pk0FreightgetFreightTermResponsePoutFreightTerm) o;
        return Objects.equals(getFreightTerm(), procOc1000pk0freightgetFreightTermResponsePoutFreightTerm.getFreightTerm()) &&
                Objects.equals(getShpitemcat(), procOc1000pk0freightgetFreightTermResponsePoutFreightTerm.getShpitemcat()) &&
                Objects.equals(getShpitemdes(), procOc1000pk0freightgetFreightTermResponsePoutFreightTerm.getShpitemdes());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getFreightTerm(),
                getShpitemcat(),
                getShpitemdes());
    }
}