/*Copyright (c) 2018-2019 cmt.mu All Rights Reserved.
 This software is the confidential and proprietary information of cmt.mu You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with cmt.mu*/
package com.mu.cmt.pfs.pfsdb.models.procedure;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/


import java.io.Serializable;
import java.util.List;
import java.util.Objects;

import com.wavemaker.runtime.data.annotations.ColumnAlias;

public class ProcOc1000pk0FreightgetLovtitleResponsePoutLovtitle implements Serializable {


    @ColumnAlias("PROMPT_TYPE")
    private String promptType;

    @ColumnAlias("LOVFLD")
    private String lovfld;

    @ColumnAlias("COL_ITEMDES2_PROMPT")
    private String colItemdes2Prompt;

    @ColumnAlias("COL_STS_PROMPT")
    private String colStsPrompt;

    @ColumnAlias("COL_ITEMDES_PROMPT")
    private String colItemdesPrompt;

    @ColumnAlias("COL_ITEMACCESS_PROMPT")
    private String colItemaccessPrompt;

    @ColumnAlias("COL_LOVDES_PROMPT")
    private String colLovdesPrompt;

    @ColumnAlias("COL_TAB_PROMPT")
    private String colTabPrompt;

    @ColumnAlias("COL_LOVFLD_PROMPT")
    private String colLovfldPrompt;

    @ColumnAlias("COL_ITEMDES3_PROMPT")
    private String colItemdes3Prompt;

    @ColumnAlias("COL_DETAILDES_PROMPT")
    private String colDetaildesPrompt;

    @ColumnAlias("COL_ITEMCOD_PROMPT")
    private String colItemcodPrompt;

    public String getPromptType() {
        return this.promptType;
    }

    public void setPromptType(String promptType) {
        this.promptType = promptType;
    }

    public String getLovfld() {
        return this.lovfld;
    }

    public void setLovfld(String lovfld) {
        this.lovfld = lovfld;
    }

    public String getColItemdes2Prompt() {
        return this.colItemdes2Prompt;
    }

    public void setColItemdes2Prompt(String colItemdes2Prompt) {
        this.colItemdes2Prompt = colItemdes2Prompt;
    }

    public String getColStsPrompt() {
        return this.colStsPrompt;
    }

    public void setColStsPrompt(String colStsPrompt) {
        this.colStsPrompt = colStsPrompt;
    }

    public String getColItemdesPrompt() {
        return this.colItemdesPrompt;
    }

    public void setColItemdesPrompt(String colItemdesPrompt) {
        this.colItemdesPrompt = colItemdesPrompt;
    }

    public String getColItemaccessPrompt() {
        return this.colItemaccessPrompt;
    }

    public void setColItemaccessPrompt(String colItemaccessPrompt) {
        this.colItemaccessPrompt = colItemaccessPrompt;
    }

    public String getColLovdesPrompt() {
        return this.colLovdesPrompt;
    }

    public void setColLovdesPrompt(String colLovdesPrompt) {
        this.colLovdesPrompt = colLovdesPrompt;
    }

    public String getColTabPrompt() {
        return this.colTabPrompt;
    }

    public void setColTabPrompt(String colTabPrompt) {
        this.colTabPrompt = colTabPrompt;
    }

    public String getColLovfldPrompt() {
        return this.colLovfldPrompt;
    }

    public void setColLovfldPrompt(String colLovfldPrompt) {
        this.colLovfldPrompt = colLovfldPrompt;
    }

    public String getColItemdes3Prompt() {
        return this.colItemdes3Prompt;
    }

    public void setColItemdes3Prompt(String colItemdes3Prompt) {
        this.colItemdes3Prompt = colItemdes3Prompt;
    }

    public String getColDetaildesPrompt() {
        return this.colDetaildesPrompt;
    }

    public void setColDetaildesPrompt(String colDetaildesPrompt) {
        this.colDetaildesPrompt = colDetaildesPrompt;
    }

    public String getColItemcodPrompt() {
        return this.colItemcodPrompt;
    }

    public void setColItemcodPrompt(String colItemcodPrompt) {
        this.colItemcodPrompt = colItemcodPrompt;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof ProcOc1000pk0FreightgetLovtitleResponsePoutLovtitle)) return false;
        final ProcOc1000pk0FreightgetLovtitleResponsePoutLovtitle procOc1000pk0freightgetLovtitleResponsePoutLovtitle = (ProcOc1000pk0FreightgetLovtitleResponsePoutLovtitle) o;
        return Objects.equals(getPromptType(), procOc1000pk0freightgetLovtitleResponsePoutLovtitle.getPromptType()) &&
                Objects.equals(getLovfld(), procOc1000pk0freightgetLovtitleResponsePoutLovtitle.getLovfld()) &&
                Objects.equals(getColItemdes2Prompt(), procOc1000pk0freightgetLovtitleResponsePoutLovtitle.getColItemdes2Prompt()) &&
                Objects.equals(getColStsPrompt(), procOc1000pk0freightgetLovtitleResponsePoutLovtitle.getColStsPrompt()) &&
                Objects.equals(getColItemdesPrompt(), procOc1000pk0freightgetLovtitleResponsePoutLovtitle.getColItemdesPrompt()) &&
                Objects.equals(getColItemaccessPrompt(), procOc1000pk0freightgetLovtitleResponsePoutLovtitle.getColItemaccessPrompt()) &&
                Objects.equals(getColLovdesPrompt(), procOc1000pk0freightgetLovtitleResponsePoutLovtitle.getColLovdesPrompt()) &&
                Objects.equals(getColTabPrompt(), procOc1000pk0freightgetLovtitleResponsePoutLovtitle.getColTabPrompt()) &&
                Objects.equals(getColLovfldPrompt(), procOc1000pk0freightgetLovtitleResponsePoutLovtitle.getColLovfldPrompt()) &&
                Objects.equals(getColItemdes3Prompt(), procOc1000pk0freightgetLovtitleResponsePoutLovtitle.getColItemdes3Prompt()) &&
                Objects.equals(getColDetaildesPrompt(), procOc1000pk0freightgetLovtitleResponsePoutLovtitle.getColDetaildesPrompt()) &&
                Objects.equals(getColItemcodPrompt(), procOc1000pk0freightgetLovtitleResponsePoutLovtitle.getColItemcodPrompt());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getPromptType(),
                getLovfld(),
                getColItemdes2Prompt(),
                getColStsPrompt(),
                getColItemdesPrompt(),
                getColItemaccessPrompt(),
                getColLovdesPrompt(),
                getColTabPrompt(),
                getColLovfldPrompt(),
                getColItemdes3Prompt(),
                getColDetaildesPrompt(),
                getColItemcodPrompt());
    }
}