/*Copyright (c) 2018-2019 cmt.mu All Rights Reserved.
 This software is the confidential and proprietary information of cmt.mu You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with cmt.mu*/
package com.mu.cmt.pfs.pfsdb.models.procedure;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/


import java.io.Serializable;
import java.util.List;
import java.util.Objects;

import com.wavemaker.runtime.data.annotations.ColumnAlias;

public class ProcRf2000pk0OclovgetCalcTotalLovResponsePoutCalcTotalLov implements Serializable {


    @ColumnAlias("CALCTOTAL")
    private String calctotal;

    public String getCalctotal() {
        return this.calctotal;
    }

    public void setCalctotal(String calctotal) {
        this.calctotal = calctotal;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof ProcRf2000pk0OclovgetCalcTotalLovResponsePoutCalcTotalLov)) return false;
        final ProcRf2000pk0OclovgetCalcTotalLovResponsePoutCalcTotalLov procRf2000pk0oclovgetCalcTotalLovResponsePoutCalcTotalLov = (ProcRf2000pk0OclovgetCalcTotalLovResponsePoutCalcTotalLov) o;
        return Objects.equals(getCalctotal(), procRf2000pk0oclovgetCalcTotalLovResponsePoutCalcTotalLov.getCalctotal());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getCalctotal());
    }
}