/*Copyright (c) 2018-2019 cmt.mu All Rights Reserved.
 This software is the confidential and proprietary information of cmt.mu You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with cmt.mu*/
package com.mu.cmt.pfs.pfsdb.models.procedure;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/


import java.io.Serializable;
import java.util.List;
import java.util.Objects;

import com.wavemaker.runtime.data.annotations.ColumnAlias;

public class ProcRf2000pk0OclovgetFreightTermsLovResponsePoutFreightLov implements Serializable {


    @ColumnAlias("FREIGHTTERM")
    private String freightterm;

    public String getFreightterm() {
        return this.freightterm;
    }

    public void setFreightterm(String freightterm) {
        this.freightterm = freightterm;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof ProcRf2000pk0OclovgetFreightTermsLovResponsePoutFreightLov)) return false;
        final ProcRf2000pk0OclovgetFreightTermsLovResponsePoutFreightLov procRf2000pk0oclovgetFreightTermsLovResponsePoutFreightLov = (ProcRf2000pk0OclovgetFreightTermsLovResponsePoutFreightLov) o;
        return Objects.equals(getFreightterm(), procRf2000pk0oclovgetFreightTermsLovResponsePoutFreightLov.getFreightterm());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getFreightterm());
    }
}