/*Copyright (c) 2018-2019 cmt.mu All Rights Reserved.
 This software is the confidential and proprietary information of cmt.mu You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with cmt.mu*/
package com.mu.cmt.pfs.pfsdb.models.procedure;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/


import java.io.Serializable;
import java.util.List;
import java.util.Objects;

import com.wavemaker.runtime.data.annotations.ColumnAlias;

public class ProcRf2000pk0OclovgetCurrencyLovResponsePoutCurrencyLov implements Serializable {


    @ColumnAlias("CURRENCY")
    private String currency;

    public String getCurrency() {
        return this.currency;
    }

    public void setCurrency(String currency) {
        this.currency = currency;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof ProcRf2000pk0OclovgetCurrencyLovResponsePoutCurrencyLov)) return false;
        final ProcRf2000pk0OclovgetCurrencyLovResponsePoutCurrencyLov procRf2000pk0oclovgetCurrencyLovResponsePoutCurrencyLov = (ProcRf2000pk0OclovgetCurrencyLovResponsePoutCurrencyLov) o;
        return Objects.equals(getCurrency(), procRf2000pk0oclovgetCurrencyLovResponsePoutCurrencyLov.getCurrency());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getCurrency());
    }
}