/*Copyright (c) 2018-2019 cmt.mu All Rights Reserved.
 This software is the confidential and proprietary information of cmt.mu You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with cmt.mu*/
package com.mu.cmt.pfs.pfsdb.models.procedure;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/


import java.io.Serializable;
import java.util.List;
import java.util.Objects;

import com.wavemaker.runtime.data.annotations.ColumnAlias;

public class ProcOc1000pk0FreightgetAllLovResponsePoutAllLov implements Serializable {


    @ColumnAlias("LOVDES")
    private String lovdes;

    @ColumnAlias("ITEMCOD")
    private String itemcod;

    @ColumnAlias("ITEMDES")
    private String itemdes;

    @ColumnAlias("ITEMDES2")
    private String itemdes2;

    @ColumnAlias("ITEMDES3")
    private String itemdes3;

    @ColumnAlias("DETAILDES")
    private String detaildes;

    public String getLovdes() {
        return this.lovdes;
    }

    public void setLovdes(String lovdes) {
        this.lovdes = lovdes;
    }

    public String getItemcod() {
        return this.itemcod;
    }

    public void setItemcod(String itemcod) {
        this.itemcod = itemcod;
    }

    public String getItemdes() {
        return this.itemdes;
    }

    public void setItemdes(String itemdes) {
        this.itemdes = itemdes;
    }

    public String getItemdes2() {
        return this.itemdes2;
    }

    public void setItemdes2(String itemdes2) {
        this.itemdes2 = itemdes2;
    }

    public String getItemdes3() {
        return this.itemdes3;
    }

    public void setItemdes3(String itemdes3) {
        this.itemdes3 = itemdes3;
    }

    public String getDetaildes() {
        return this.detaildes;
    }

    public void setDetaildes(String detaildes) {
        this.detaildes = detaildes;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof ProcOc1000pk0FreightgetAllLovResponsePoutAllLov)) return false;
        final ProcOc1000pk0FreightgetAllLovResponsePoutAllLov procOc1000pk0freightgetAllLovResponsePoutAllLov = (ProcOc1000pk0FreightgetAllLovResponsePoutAllLov) o;
        return Objects.equals(getLovdes(), procOc1000pk0freightgetAllLovResponsePoutAllLov.getLovdes()) &&
                Objects.equals(getItemcod(), procOc1000pk0freightgetAllLovResponsePoutAllLov.getItemcod()) &&
                Objects.equals(getItemdes(), procOc1000pk0freightgetAllLovResponsePoutAllLov.getItemdes()) &&
                Objects.equals(getItemdes2(), procOc1000pk0freightgetAllLovResponsePoutAllLov.getItemdes2()) &&
                Objects.equals(getItemdes3(), procOc1000pk0freightgetAllLovResponsePoutAllLov.getItemdes3()) &&
                Objects.equals(getDetaildes(), procOc1000pk0freightgetAllLovResponsePoutAllLov.getDetaildes());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getLovdes(),
                getItemcod(),
                getItemdes(),
                getItemdes2(),
                getItemdes3(),
                getDetaildes());
    }
}