/*Copyright (c) 2018-2019 cmt.mu All Rights Reserved.
 This software is the confidential and proprietary information of cmt.mu You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with cmt.mu*/
package com.mu.cmt.pfs.pfsdb.service;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/


import com.mu.cmt.pfs.pfsdb.models.procedure.*;

public interface PfsdbProcedureExecutorService {

    ProcRf2000pk0OclovgetCalcTotalLovResponse executeProcRF2000PK0_OCLOVGetCalcTotalLOV(String pprgId);

    ProcRf2000pk0OclovgetCalcMethodLovResponse executeProcRF2000PK0_OCLOVGetCalcMethodLOV(String pprgId);

    ProcRf2000pk0OclovgetCurrencyLovResponse executeProcRF2000PK0_OCLOVGetCurrencyLOV(String pprgId, String pfcountry, String ptcountry);

    ProcRf2000pk0OclovgetFreightTermsLovResponse executeProcRF2000PK0_OCLOVGetFreightTermsLOV(String pprgId);

    Void executeProcOC1000PK0_FREIGHTInsFreightDetails(String pprgId, String pctycod, String pshpdestctycod, String pshpTyp, String pshpdest, String pforwardern, String pcontainerTyp);

    Void executeProcOC1000PK0_FREIGHTUpdClientShp(String pprgId, String pclient, Integer pseqNr, String pfreightTerm, String pshpdest, String pshpdestctycod);

    Void executeProcOC1000PK0_FREIGHTInsCostDetails(String pprgId, String pctycod, String pshpTyp, String pforwardern, String pshpdest, String pitemcat, String pitemdes, String pcontainerTpy, String pqtyUom, Double pqtyFrom, Double pqtyTo, String pcalcMethod, String pcurrencyCod, Double pcurPerUnit, String pfreightSts, String pshpdestctycod, Double pcurperitem, String pcalcPercent, String pcalcSubTotalTyp, String psubtotalTyp);

    ProcOc1000pk0FreightgetCostDetailsResponse executeProcOC1000PK0_FREIGHTGetCostDetails(String pprgId, String pctycod, String pshpTyp, String pshpdestctycod);

    ProcRf2000pk0OclovgetAllLovResponse executeProcRF2000PK0_OCLOVGetAllLOV(String pprgId);

    ProcRf2000pk0OclovgetItemCatLovResponse executeProcRF2000PK0_OCLOVGetItemCatLOV(String pprgId);

    ProcRf2000pk0OrlovgetCligrpResponse executeProcRF2000PK0_ORLOVGetCligrp(String pprgid);

    ProcRf2000pk0OclovgetShpDestLovResponse executeProcRF2000PK0_OCLOVGetShpDestLOV(String pprgId);

    ProcRf2000pk0OrlovgetOrdCtycodLovResponse executeProcRF2000PK0_ORLOVGetOrdCtycodLOV(String pprgid);

    Void executeProcOC1000PK0_FREIGHTDelFreightDetails(String pprgId, String pctycod, String pshpdestctycod, Integer pshpseq);

    ProcRf2000pk0OclovgetAllCountryLovResponse executeProcRF2000PK0_OCLOVGetAllCountryLOV(String pprgId);

    Void executeProcOC1000PK0_FREIGHTUpdCostDetails(String pprgId, String pctycod, String pshptyp, Integer pfreightseqnr, String pshpdestctycod, String pitemdes, String pcalcmethod, String pqtyUom, Double pcurperunit, Double pcurperitem, String pcurrency, Double pqtyfrom, Double pqtyto, Double pcalcpercent, String pcalctotal, String psubtotal, Integer psortseq);

    Void executeProcOC1000PK0_FREIGHTCancelCostDetails(String pprgId, String pctycod, String pshptyp, Integer pfreightseqnr);

    ProcOc1000pk0FreightgetClientShpResponse executeProcOC1000PK0_FREIGHTGetClientShp(String pprgId, String pcligrp, String pclient, String pfreightTerm);

    ProcOc1000pk0FreightgetFreightTermResponse executeProcOC1000PK0_FREIGHTGetFreightTerm(String pprgId, String pfreightTerm, String pshpitemcat);

    ProcRf2000pk0OclovgetShpTypLovResponse executeProcRF2000PK0_OCLOVGetShpTypLOV(String pprgId);

    ProcRf2000pk0OclovgetShpContLovResponse executeProcRF2000PK0_OCLOVGetShpContLOV(String pprgId);

    Void executeProcOC1000PK0_FREIGHTDelClientShp(String pprgId, String pclient, Integer pseqNr, String pfreightTerm);

    ProcOc1000pk0FreightgetAllLovResponse executeProcOC1000PK0_FREIGHTGetAllLOV(String pprgId, String pitemcod, String pfcountry, String ptcountry);

    ProcOc1000pk0FreightgetFreightDetailsResponse executeProcOC1000PK0_FREIGHTGetFreightDetails(String pprgId, String pctycod, String pshpdestctycod, String pshptyp);

    ProcOc1000pk0FreightgetLovtitleResponse executeProcOC1000PK0_FREIGHTGetLOVTitle(String pprgId, String plovfld, String ppromptType);

    ProcRf2000pk0OclovgetQtyUomLovResponse executeProcRF2000PK0_OCLOVGetQtyUomLOV(String pprgId, String pcalcMethod);

    Void executeProcOC1000PK0_FREIGHTInsClientShp(String pprgId, String pclient, String pfreightTerm, String pfromCounty, String pshpdest, String pshpdestctycod);

    ProcRf2000pk0OclovgetShpTypCostLovResponse executeProcRF2000PK0_OCLOVGetShpTypCostLOV(String pprgId);

    ProcRf2000pk0OclovgetClicodLovResponse executeProcRF2000PK0_OCLOVGetClicodLOV(String pprgid, String pcligrp);

    ProcRf2000pk0OclovgetAllShpDestLovResponse executeProcRF2000PK0_OCLOVGetAllShpDestLOV(String pprgId);

}